import React, { ChangeEvent, useEffect, useState, useTransition } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import ART from 'data/art.json';
import FilterHelper from 'helper/filter';
import SearchInput from 'components/SearchInput';
import ListItem from 'components/ListItem';
import BackgroundAnimation from 'components/BackgroundAnimation';

const Home: NextPage = () => {
  const [isPending, startTransition] = useTransition();

  const [query, setQuery] = useState<string>('');
  const [arts, setArts] = useState<Array<ArtDataType>>(ART.data);

  const changeHandler = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    if (name === 'query') {
      setQuery(value);

      startTransition(() => {
        const _arts = FilterHelper.withKey(ART.data, value);
        setArts(_arts);
      });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BackgroundAnimation />
      <main className='absolute w-screen'>
        <div className='mx-auto w-full max-w-screen-lg px-10 md:px-20 xl:px-0'>
          {/* TODO: Show the 4 pieces of art along with their details */}
          <form className='pt-16 lg:pt-40'>
            {/* TODO: Filter art */}
            <h1 className='text-center text-red-400 font-bold text-[36px] lg:text-[56px]'>
              Image Gallery
            </h1>
            <SearchInput query={query} onChange={changeHandler} />
          </form>
          <div className='mt-10 lg:mt-24 mb-20 grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-10'>
            {/* TODO: List of art */}
            {arts.map((art, index) => (
              <ListItem {...art} key={art.description} index={index} />
            ))}
          </div>
          {arts.length === 0 && (
            <p className='w-full text-center text-lg'>
              <span className='pb-10 block text-[56px] font-bold'>
                \ ( ^ Д ^ ) /
              </span>
              <span>No results, try again with other keywords</span>
              <br />
            </p>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
